apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-app-chart.fullname" . }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    {{- include "microservice-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "microservice-app-chart.selectorLabels" . | nindent 4 }}
